client_config_backend: file
client_config_file: /home/matheus/Trabalho/facily/labs/automations/src/services/google_drive/client_secrets.json

save_credentials: True
save_credentials_backend: file
save_credentials_file: /home/matheus/Trabalho/facily/labs/automations/src/services/google_drive/credentials.txt

get_refresh_token: True
oauth_scope:
  - https://www.googleapis.com/auth/drive
  - https://www.googleapis.com/auth/drive.install
